version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=osgb
      - POSTGRES_USER=osgb
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/osgb

    volumes:
      - ./postgres/backup:/var/lib/postgresql/data/backup
      - postgres:/var/lib/postgresql/data/osgb
    networks:
      - osgbnet
    ports:
      - "5432:5432"
    restart: always
    command: -p 5432

volumes: 
  postgres:
networks:
  osgbnet: