version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=osgb
      - MONGO_INITDB_ROOT_USERNAME=osgb
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongodb:/data/db
    networks:
      - osgbnet
    ports:
      - "27017:27017"

volumes: 
  mongodb:
networks:
  osgbnet: